### ISSUE TITLE
坑啊！缺文件Version

### ISSUE THREAD

**Issue by cwjfeifei** [baiiu/TSnackbar#1]
坑啊！缺文件Version

**Comment by baiiu** [comment]
@cwjfeifei 什么意思

**Comment by daxiaohuzi** [comment]
楼主 你代码中缺少Version的文件 LUtils.hasL()这个方法也是没有的 然后就不能运行了 我QQ2391684562 如果有需要的话 楼主可以联系这个

**Comment by baiiu** [comment]
噢，我看看

**Comment by baiiu** [comment]
哦，不好意思。AS的提交工具没add进来，现在提上去了。
